esphome:
  name: tester2
  friendly_name: Tester2

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XQTRcwlcMiLItCSJy1uxHaGBIZa+cwHocO/Lmq0/OI0="

ota:
  - platform: esphome
    password: "d79992c6a88772c464d755ca91adcd07"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tester2 Fallback Hotspot"
    password: "CPSzCPzidcBg"

captive_portal:

web_server:
  port: 80

i2c:
  sda: 17
  scl: 18
  frequency: 700kHz
  scan: true

# font:
#   - file: "fonts/arial.ttf"
#     id: font1
#     size: 8

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    reset_pin: 21
    update_interval: 15s
    lambda: |-
      it.line(0, 0, 50, 50);
