esphome:
  name: tester
  friendly_name: Tester

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DUGLcSuFw1EDzs3+mu3Jn+CZi+bSU1Gvbh1N41Co7zE="

ota:
  - platform: esphome
    password: "e76fc819eaa1eea2de34dce7176b6e0e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tester Fallback Hotspot"
    password: "r5V6DrQ8O8Mg"

captive_portal:

web_server:
  port: 80

i2c:
  sda: 17
  scl: 18
  frequency: 700kHz
  scan: true

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "Test Button"
    interrupt_type: RISING
    id: test_button

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    reset_pin: 21
    update_interval: 15s
    lambda: |-
      if (id(test_button).state) {
        it.print(0, 0, id(roboto), "Button Pressed");
      } else {
        it.print(0, 0, id(roboto), "Button Released");
      }
